# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitioyFrencuencia',
            new_name='SitioyFrecuencia',
        ),
    ]
