# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170820_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busqueda',
        ),
    ]
